<?xml version="1.0" encoding="UTF=8"?>
<!DOCTYPE usuarios [
<!ELEMENT usuarios (cliente*,vendedor)>
    <!ELEMENT cliente (nombre,contraseña,carrito)>
     <!ATTLIST cliente mail ID #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT contraseña (#PCDATA)>
        <!ELEMENT carrito (camiseta*,botas*,pantalones*,conjunto*,guantes*)>
         <!ELEMENT camiseta (nombre,dorsal,talla,precio,stock,tipo)>
     <!ATTLIST camiseta id (CamLocal | CamVisitante) #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT dorsal (#PCDATA)>
        <!ELEMENT talla (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT stock (#PCDATA)>
        <!ELEMENT tipo (#PCDATA)>
     <!ELEMENT pantalon (dorsal,talla,precio,publicado,stock,longitud)>
     <!ATTLIST pantalon id (PantCorto | PantChandal) #REQUIRED>
     <!ELEMENT tipo (#PCDATA)>
     <!ELEMENT botas (modelo,marca,color,talla,precio,stock)>
      <!ATTLIST botas id CDATA #FIXED "Botas">
     <!ELEMENT modelo (#PCDATA)>
     <!ELEMENT marca (#PCDATA)>
     <!ELEMENT color (#PCDATA)>
     <!ELEMENT conjunto (dorsal,talla,precio,stock,tipo)>
     <!ATTLIST conjunto id (ConLocal | ConVisitante) #REQUIRED>
     <!ELEMENT guantes (modelo,marca,color,adherencia,talla,precio,stock)>
     <!ATTLIST botas id CDATA #FIXED "Guantes">
    <!ELEMENT vendedor (nombre,contraseña)>
     <!ATTLIST vendedor mail ID #REQUIRED>
]>
<usuarios>
    <cliente mail="cmoril@ucm.es">
        <nombre>cris</nombre>
        <contraseña>123</contraseña>
        <carrito>
                <camiseta id="CamVisitante">
                <nombre>Messi</nombre>
                <dorsal>10</dorsal>
                <talla>L</talla>
                <precio>80</precio>
                <stock>23</stock>
                <tipo>visitante</tipo>
            </camiseta>
         </carrito>
    </cliente>
     <cliente mail="sergioat@ucm.es">
        <nombre>sergio</nombre>
        <contraseña>456</contraseña>
        <carrito>
        </carrito>
    </cliente>
     <vendedor mail="admin@ucm.es">
        <nombre>admin</nombre>
        <contraseña>000</contraseña>
    </vendedor>
</usuarios>